### ISSUE TITLE
`polytone` should be imported to `ibc-apps` repo.

### ISSUE THREAD

**Issue by Reecepbcups** [cosmos/ibc-apps#149]
From Jake / noah,

https://github.com/DA0-DA0/polytone

# TODO
- [ ] Wiki Content copy paste
- [ ] issue pull over
- Add to @cosmos/daodao_ibc-apps_write -> Noah, Jake, Artimix, and bekauz
- [x] getting them in as codeowners
- [x] Artifact Publish on tag of cosmwasm/polytone

**Comment by jonathanpberger** [comment]
DAODAO team will review and ship the PR.

**Comment by jtieri** [comment]
I believe this can be closed as of #169? cc @Reecepbcups
